slack_token: ""
channel: ""
cols:
  - id
  - title
  - categories
  - abstract
  - doi
  - created
  - updated
  - authors
categories:
  - physics
  - quant-ph
  - cond-mat
  - physics
subcat:
  - [physics.atom-ph]
  - []
  - [cond-mat.quant-gas]
  - [physics.optics]